### ISSUE TITLE
Support for Presets

### ISSUE THREAD

**Issue by rohankapoorcom** [tjhorner/wifi-desk-controller#5]
Hi TJ,

Is it possible for you to add functionality for programming and recalling presets for desks that support that?

Thanks!

**Comment by tjhorner** [comment]
Yes, definitely possible, just haven't gotten around to it yet. I will plan this for a future version of the firmware.

**Comment by rohankapoorcom** [comment]
Awesome! I'm trying to avoid manually keeping the scenes in Home Assistant in sync with the desk so it's easier if the preset is directly exposed from the desk as a scene in Home Assistant.

**Comment by rohankapoorcom** [comment]
I have an Uplift V2 (but I don't have my desk controller board yet, ordered it from your tindie store last week).

**Comment by tjhorner** [comment]
I just added support for recalling presets in the 0.1.1 release. I'm not sure how I would add support for programming presets, but that doesn't sound like a very common use case to me, since it's a very one-and-done type of thing. If you need support for this I can open another issue

**Comment by rohankapoorcom** [comment]
Awesome! I got my controller today and tested it out and it works great. Thanks so much!

**Comment by tjhorner** [comment]
Glad to hear it! Let me know if you need anything else 👍
